"""audit log, purpose, consent, retention tracking

Revision ID: 18e3f127bef9
Revises: fd37165e7d99
Create Date: 2026-07-22 10:27:32.000976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e3f127bef9'
down_revision: Union[str, None] = 'fd37165e7d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('datasets', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('datasets', sa.Column('purpose', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('consent_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'consent_status')
    op.drop_column('datasets', 'purpose')
    op.drop_column('datasets', 'created_at')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
