"""initial schema with multi-tenant orgs

Revision ID: 6e9ba7d34bd6
Revises: 
Create Date: 2026-07-22 09:57:43.260740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.encrypted_types


# revision identifiers, used by Alembic.
revision: str = '6e9ba7d34bd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('business_glossary_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'term', name='uq_glossary_term_per_org')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('connection_config', app.db.encrypted_types.EncryptedJSON(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('schema_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('steward', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('certification', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('columns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('sensitivity_score', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detection_reason', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('uniqueness', sa.Float(), nullable=True),
    sa.Column('validity', sa.Float(), nullable=True),
    sa.Column('freshness', sa.Float(), nullable=True),
    sa.Column('consistency', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.create_table('dataset_lineage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upstream_dataset_id', sa.String(length=36), nullable=True),
    sa.Column('downstream_dataset_id', sa.String(length=36), nullable=True),
    sa.Column('transformation_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['downstream_dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['upstream_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_lineage')
    op.drop_table('data_quality')
    op.drop_table('columns')
    op.drop_table('datasets')
    op.drop_table('users')
    op.drop_table('data_sources')
    op.drop_table('business_glossary_terms')
    op.drop_table('organizations')
    # ### end Alembic commands ###
