"""phase1 privacy and retention metadata

Revision ID: fd37165e7d99
Revises: 6e9ba7d34bd6
Create Date: 2026-07-22 10:16:47.734839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd37165e7d99'
down_revision: Union[str, None] = '6e9ba7d34bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('dpdp_category', sa.String(), nullable=True))
    op.add_column('columns', sa.Column('consent_required', sa.Boolean(), nullable=True))
    op.add_column('columns', sa.Column('classification_source', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('retention_period_days', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('retention_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'retention_notes')
    op.drop_column('datasets', 'retention_period_days')
    op.drop_column('columns', 'classification_source')
    op.drop_column('columns', 'consent_required')
    op.drop_column('columns', 'dpdp_category')
    # ### end Alembic commands ###
